
import java.text.MessageFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DANIEL PASIGAN
 */
public class CISOrderingSystem extends javax.swing.JFrame {

    private int i;

    
    public String[] getData = new String[1];
    /**
     * Creates new form Try
     */
    public CISOrderingSystem() {
        initComponents();
    }
    
    public void postData(){
        this.jTF4.setText(getData[0]);
    }

    
   
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel31 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jTj1 = new javax.swing.JButton();
        jTtwo = new javax.swing.JButton();
        jTNikefly = new javax.swing.JButton();
        jTNikeHBR = new javax.swing.JButton();
        jTjD = new javax.swing.JButton();
        jTJC = new javax.swing.JButton();
        jTjPuma = new javax.swing.JButton();
        jTNikeAlumni = new javax.swing.JButton();
        jTlebron = new javax.swing.JButton();
        jTjS = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton110 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jButton118 = new javax.swing.JButton();
        jButton119 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jButton121 = new javax.swing.JButton();
        jButton122 = new javax.swing.JButton();
        jButton123 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jButton124 = new javax.swing.JButton();
        jButton125 = new javax.swing.JButton();
        jButton126 = new javax.swing.JButton();
        jButton127 = new javax.swing.JButton();
        jButton128 = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButton130 = new javax.swing.JButton();
        jButton131 = new javax.swing.JButton();
        jButton132 = new javax.swing.JButton();
        jButton133 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jButton134 = new javax.swing.JButton();
        jButton135 = new javax.swing.JButton();
        jButton136 = new javax.swing.JButton();
        jButton137 = new javax.swing.JButton();
        jButton138 = new javax.swing.JButton();
        jButton139 = new javax.swing.JButton();
        jButton140 = new javax.swing.JButton();
        jButton141 = new javax.swing.JButton();
        jButton142 = new javax.swing.JButton();
        jButton143 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jButton144 = new javax.swing.JButton();
        jButton145 = new javax.swing.JButton();
        jButton146 = new javax.swing.JButton();
        jButton147 = new javax.swing.JButton();
        jButton148 = new javax.swing.JButton();
        jButton149 = new javax.swing.JButton();
        jButton150 = new javax.swing.JButton();
        jButton151 = new javax.swing.JButton();
        jButton152 = new javax.swing.JButton();
        jButton153 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jButton154 = new javax.swing.JButton();
        jButton155 = new javax.swing.JButton();
        jButton156 = new javax.swing.JButton();
        jButton157 = new javax.swing.JButton();
        jButton158 = new javax.swing.JButton();
        jButton159 = new javax.swing.JButton();
        jButton160 = new javax.swing.JButton();
        jButton161 = new javax.swing.JButton();
        jButton162 = new javax.swing.JButton();
        jButton163 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jButton164 = new javax.swing.JButton();
        jButton165 = new javax.swing.JButton();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jS10 = new javax.swing.JSpinner();
        jS2 = new javax.swing.JSpinner();
        jS1 = new javax.swing.JSpinner();
        jS5 = new javax.swing.JSpinner();
        jS6 = new javax.swing.JSpinner();
        jS7 = new javax.swing.JSpinner();
        jS3 = new javax.swing.JSpinner();
        jS8 = new javax.swing.JSpinner();
        jS9 = new javax.swing.JSpinner();
        jS4 = new javax.swing.JSpinner();
        jTj4 = new javax.swing.JButton();
        JTNew = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jS11 = new javax.swing.JSpinner();
        jS12 = new javax.swing.JSpinner();
        sale25 = new javax.swing.JCheckBox();
        sale70 = new javax.swing.JCheckBox();
        sale = new javax.swing.JCheckBox();
        sale10 = new javax.swing.JCheckBox();
        flash = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jTF1 = new javax.swing.JTextField();
        jTF2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jTF5 = new javax.swing.JTextField();
        jCBPayment = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pwd = new javax.swing.JCheckBox();
        senior = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jBP = new javax.swing.JButton();
        jBpay = new javax.swing.JButton();
        jBR = new javax.swing.JButton();
        jBremove = new javax.swing.JButton();
        jBExit = new javax.swing.JButton();
        jBExit1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jR = new javax.swing.JTextArea();
        jLBL1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 520, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 270, -1));

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTj1.setBackground(new java.awt.Color(204, 204, 204));
        jTj1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTj1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\ref.jpg")); // NOI18N
        jTj1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTj1ActionPerformed(evt);
            }
        });
        jPanel16.add(jTj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 60));

        jTtwo.setBackground(new java.awt.Color(204, 204, 204));
        jTtwo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTtwo.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\bread.jpg")); // NOI18N
        jTtwo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTtwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtwoActionPerformed(evt);
            }
        });
        jPanel16.add(jTtwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 110, 60));

        jTNikefly.setBackground(new java.awt.Color(204, 204, 204));
        jTNikefly.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTNikefly.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\air.jpg")); // NOI18N
        jTNikefly.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTNikefly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNikeflyActionPerformed(evt);
            }
        });
        jPanel16.add(jTNikefly, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 110, 60));

        jTNikeHBR.setBackground(new java.awt.Color(204, 204, 204));
        jTNikeHBR.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTNikeHBR.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\micro.jpg")); // NOI18N
        jTNikeHBR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTNikeHBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNikeHBRActionPerformed(evt);
            }
        });
        jPanel16.add(jTNikeHBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 60));

        jTjD.setBackground(new java.awt.Color(204, 204, 204));
        jTjD.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTjD.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\electricfan.jpg")); // NOI18N
        jTjD.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTjD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTjDActionPerformed(evt);
            }
        });
        jPanel16.add(jTjD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 60));

        jTJC.setBackground(new java.awt.Color(204, 204, 204));
        jTJC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTJC.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\blender.jpg")); // NOI18N
        jTJC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTJC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTJCActionPerformed(evt);
            }
        });
        jPanel16.add(jTJC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 110, 60));

        jTjPuma.setBackground(new java.awt.Color(204, 204, 204));
        jTjPuma.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTjPuma.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\vacum.jpg")); // NOI18N
        jTjPuma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTjPuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTjPumaActionPerformed(evt);
            }
        });
        jPanel16.add(jTjPuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 110, 60));

        jTNikeAlumni.setBackground(new java.awt.Color(204, 204, 204));
        jTNikeAlumni.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTNikeAlumni.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\water.jpg")); // NOI18N
        jTNikeAlumni.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTNikeAlumni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNikeAlumniActionPerformed(evt);
            }
        });
        jPanel16.add(jTNikeAlumni, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 110, 60));

        jTlebron.setBackground(new java.awt.Color(204, 204, 204));
        jTlebron.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTlebron.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\tv.jpg")); // NOI18N
        jTlebron.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTlebron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlebronActionPerformed(evt);
            }
        });
        jPanel16.add(jTlebron, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 110, 60));

        jTjS.setBackground(new java.awt.Color(204, 204, 204));
        jTjS.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTjS.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\rice.jpg")); // NOI18N
        jTjS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTjS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTjSActionPerformed(evt);
            }
        });
        jPanel16.add(jTjS, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, 60));

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton104.setBackground(new java.awt.Color(204, 204, 204));
        jButton104.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton104.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton105.setBackground(new java.awt.Color(204, 204, 204));
        jButton105.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton105.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton106.setBackground(new java.awt.Color(204, 204, 204));
        jButton106.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton106.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton106ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton107.setBackground(new java.awt.Color(204, 204, 204));
        jButton107.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton107.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton108.setBackground(new java.awt.Color(204, 204, 204));
        jButton108.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton108.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton109.setBackground(new java.awt.Color(204, 204, 204));
        jButton109.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton109.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton110.setBackground(new java.awt.Color(204, 204, 204));
        jButton110.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton110.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton111.setBackground(new java.awt.Color(204, 204, 204));
        jButton111.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton111.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton112.setBackground(new java.awt.Color(204, 204, 204));
        jButton112.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton112.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton113.setBackground(new java.awt.Color(204, 204, 204));
        jButton113.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton113.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton114.setBackground(new java.awt.Color(204, 204, 204));
        jButton114.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton114.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton115.setBackground(new java.awt.Color(204, 204, 204));
        jButton115.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton115.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton116.setBackground(new java.awt.Color(204, 204, 204));
        jButton116.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton116.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton116ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton116, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton117.setBackground(new java.awt.Color(204, 204, 204));
        jButton117.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton117.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton117, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton118.setBackground(new java.awt.Color(204, 204, 204));
        jButton118.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton118.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton118, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton119.setBackground(new java.awt.Color(204, 204, 204));
        jButton119.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton119.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton119, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton120.setBackground(new java.awt.Color(204, 204, 204));
        jButton120.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton120.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton120, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton121.setBackground(new java.awt.Color(204, 204, 204));
        jButton121.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton121.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton121, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton122.setBackground(new java.awt.Color(204, 204, 204));
        jButton122.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton122.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton122, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton123.setBackground(new java.awt.Color(204, 204, 204));
        jButton123.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton123.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel18.add(jButton123, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton124.setBackground(new java.awt.Color(204, 204, 204));
        jButton124.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton124.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton124, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton125.setBackground(new java.awt.Color(204, 204, 204));
        jButton125.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton125.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton125, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton126.setBackground(new java.awt.Color(204, 204, 204));
        jButton126.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton126.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton126ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton126, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton127.setBackground(new java.awt.Color(204, 204, 204));
        jButton127.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton127.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton127, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton128.setBackground(new java.awt.Color(204, 204, 204));
        jButton128.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton128.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton128, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton129.setBackground(new java.awt.Color(204, 204, 204));
        jButton129.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton129.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton129, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton130.setBackground(new java.awt.Color(204, 204, 204));
        jButton130.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton130.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton130, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton131.setBackground(new java.awt.Color(204, 204, 204));
        jButton131.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton131.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton131, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton132.setBackground(new java.awt.Color(204, 204, 204));
        jButton132.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton132.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton132, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton133.setBackground(new java.awt.Color(204, 204, 204));
        jButton133.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton133.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel19.add(jButton133, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel16.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton134.setBackground(new java.awt.Color(204, 204, 204));
        jButton134.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton134.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton134, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton135.setBackground(new java.awt.Color(204, 204, 204));
        jButton135.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton135.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton135, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton136.setBackground(new java.awt.Color(204, 204, 204));
        jButton136.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton136.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton136ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton136, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton137.setBackground(new java.awt.Color(204, 204, 204));
        jButton137.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton137.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton137, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton138.setBackground(new java.awt.Color(204, 204, 204));
        jButton138.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton138.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton138, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton139.setBackground(new java.awt.Color(204, 204, 204));
        jButton139.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton139.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton139, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton140.setBackground(new java.awt.Color(204, 204, 204));
        jButton140.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton140.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton140, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton141.setBackground(new java.awt.Color(204, 204, 204));
        jButton141.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton141.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton141, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton142.setBackground(new java.awt.Color(204, 204, 204));
        jButton142.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton142.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton142, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton143.setBackground(new java.awt.Color(204, 204, 204));
        jButton143.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton143.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel20.add(jButton143, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton144.setBackground(new java.awt.Color(204, 204, 204));
        jButton144.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton144.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton144, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton145.setBackground(new java.awt.Color(204, 204, 204));
        jButton145.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton145.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton145, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton146.setBackground(new java.awt.Color(204, 204, 204));
        jButton146.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton146.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton146.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton146ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton146, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton147.setBackground(new java.awt.Color(204, 204, 204));
        jButton147.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton147.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton147, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton148.setBackground(new java.awt.Color(204, 204, 204));
        jButton148.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton148.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton148, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton149.setBackground(new java.awt.Color(204, 204, 204));
        jButton149.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton149.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton149, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton150.setBackground(new java.awt.Color(204, 204, 204));
        jButton150.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton150.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton150, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton151.setBackground(new java.awt.Color(204, 204, 204));
        jButton151.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton151.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton151, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton152.setBackground(new java.awt.Color(204, 204, 204));
        jButton152.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton152.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton152, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton153.setBackground(new java.awt.Color(204, 204, 204));
        jButton153.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton153.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel21.add(jButton153, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton154.setBackground(new java.awt.Color(204, 204, 204));
        jButton154.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton154.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton154, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton155.setBackground(new java.awt.Color(204, 204, 204));
        jButton155.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton155.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton155, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton156.setBackground(new java.awt.Color(204, 204, 204));
        jButton156.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton156.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton156.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton156ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton156, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton157.setBackground(new java.awt.Color(204, 204, 204));
        jButton157.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton157.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton157, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton158.setBackground(new java.awt.Color(204, 204, 204));
        jButton158.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton158.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton158, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton159.setBackground(new java.awt.Color(204, 204, 204));
        jButton159.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton159.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton159, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton160.setBackground(new java.awt.Color(204, 204, 204));
        jButton160.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton160.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton160, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton161.setBackground(new java.awt.Color(204, 204, 204));
        jButton161.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton161.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton161, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton162.setBackground(new java.awt.Color(204, 204, 204));
        jButton162.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton162.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton162, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton163.setBackground(new java.awt.Color(204, 204, 204));
        jButton163.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton163.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.add(jButton163, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton164.setBackground(new java.awt.Color(204, 204, 204));
        jButton164.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton164.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton164, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 80));

        jButton165.setBackground(new java.awt.Color(204, 204, 204));
        jButton165.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton165.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton165, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 80));

        jButton166.setBackground(new java.awt.Color(204, 204, 204));
        jButton166.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton166.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton166.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton166ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton166, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 80));

        jButton167.setBackground(new java.awt.Color(204, 204, 204));
        jButton167.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton167.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton167, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, 80));

        jButton168.setBackground(new java.awt.Color(204, 204, 204));
        jButton168.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton168.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton168, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, 80));

        jButton169.setBackground(new java.awt.Color(204, 204, 204));
        jButton169.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton169.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton169, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 110, 80));

        jButton170.setBackground(new java.awt.Color(204, 204, 204));
        jButton170.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton170.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton170, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 110, 80));

        jButton171.setBackground(new java.awt.Color(204, 204, 204));
        jButton171.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton171.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton171, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, 80));

        jButton172.setBackground(new java.awt.Color(204, 204, 204));
        jButton172.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton172.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton172, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 80));

        jButton173.setBackground(new java.awt.Color(204, 204, 204));
        jButton173.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton173.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel23.add(jButton173, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 110, 80));

        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jPanel16.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 490, 290));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("₱ 40,000");
        jPanel16.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("₱ 35,000");
        jPanel16.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("₱ 5,000");
        jPanel16.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("₱ 7,000");
        jPanel16.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 80, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("₱ 2,000");
        jPanel16.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 80, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("₱ 2,500");
        jPanel16.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 80, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("₱ 3,000");
        jPanel16.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 80, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("₱ 2,000");
        jPanel16.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 80, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("₱ 3000");
        jPanel16.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 80, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("₱ 20,000");
        jPanel16.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 80, -1));
        jPanel16.add(jS10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 40, 20));
        jPanel16.add(jS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 40, 20));
        jPanel16.add(jS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 40, 20));
        jPanel16.add(jS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 20));
        jPanel16.add(jS6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 40, 20));
        jPanel16.add(jS7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 40, 20));
        jPanel16.add(jS3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 40, 20));
        jPanel16.add(jS8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 40, 20));
        jPanel16.add(jS9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 40, 20));
        jPanel16.add(jS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 40, 20));

        jTj4.setBackground(new java.awt.Color(204, 204, 204));
        jTj4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jTj4.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\washing.jpg")); // NOI18N
        jTj4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTj4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTj4ActionPerformed(evt);
            }
        });
        jPanel16.add(jTj4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, 60));

        JTNew.setBackground(new java.awt.Color(204, 204, 204));
        JTNew.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JTNew.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Documents\\discrete_pictures\\Stove.jpg")); // NOI18N
        JTNew.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JTNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNewActionPerformed(evt);
            }
        });
        jPanel16.add(JTNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 60));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("₱ 40,000");
        jPanel16.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("₱ 2,500");
        jPanel16.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 80, -1));
        jPanel16.add(jS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 40, 20));
        jPanel16.add(jS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 40, 20));

        sale25.setText("25%");
        sale25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale25ActionPerformed(evt);
            }
        });
        jPanel16.add(sale25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 20));

        sale70.setText("70%");
        sale70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale70ActionPerformed(evt);
            }
        });
        jPanel16.add(sale70, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 50, 20));

        sale.setText("50%");
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });
        jPanel16.add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, 20));

        sale10.setText("10%");
        sale10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sale10ActionPerformed(evt);
            }
        });
        jPanel16.add(sale10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 50, 20));

        flash.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        flash.setText("Super Sale 70%  for all products");
        flash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flashActionPerformed(evt);
            }
        });
        jPanel16.add(flash, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 330, -1));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 500, 370));

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel10.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1010, 150));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1010, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Total:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("SubTotal:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tax:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 40));

        jTF3.setEditable(false);
        jTF3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTF3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(jTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, 30));

        jTF1.setEditable(false);
        jTF1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTF1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 170, 30));

        jTF2.setEditable(false);
        jTF2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTF2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("₱");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 30, 50));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("₱");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 30, 50));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("₱");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 30, 50));

        jPanel10.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 150));

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1010, 150));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Payment:");
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cash:");
        jPanel12.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Change:");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 80, 40));

        jTF4.setEditable(false);
        jTF4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTF4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF4ActionPerformed(evt);
            }
        });
        jPanel12.add(jTF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 170, 30));

        jTF5.setEditable(false);
        jTF5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTF5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF5ActionPerformed(evt);
            }
        });
        jPanel12.add(jTF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, 30));

        jCBPayment.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCBPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "G-Cash" }));
        jCBPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPaymentActionPerformed(evt);
            }
        });
        jPanel12.add(jCBPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("₱");
        jPanel12.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 30, 50));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("₱");
        jPanel12.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 30, 50));

        pwd.setText("PWD");
        pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdActionPerformed(evt);
            }
        });
        jPanel12.add(pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        senior.setText("Senior");
        senior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorActionPerformed(evt);
            }
        });
        jPanel12.add(senior, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jPanel10.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 320, 150));

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel14.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1010, 150));

        jBP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBP.setText("Print");
        jBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPActionPerformed(evt);
            }
        });
        jPanel14.add(jBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        jBpay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBpay.setText("Pay");
        jBpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpayActionPerformed(evt);
            }
        });
        jPanel14.add(jBpay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jBR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBR.setText("Reset");
        jBR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRActionPerformed(evt);
            }
        });
        jPanel14.add(jBR, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 110, -1));

        jBremove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBremove.setText("Remove");
        jBremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoveActionPerformed(evt);
            }
        });
        jPanel14.add(jBremove, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, 30));

        jBExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBExit.setText("Place Order");
        jBExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitActionPerformed(evt);
            }
        });
        jPanel14.add(jBExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        jBExit1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jBExit1.setText("Exit");
        jBExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExit1ActionPerformed(evt);
            }
        });
        jPanel14.add(jBExit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, 40));

        jPanel10.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 280, 140));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 1020, 190));

        jR.setEditable(false);
        jR.setColumns(20);
        jR.setRows(5);
        jScrollPane3.setViewportView(jR);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 310, 530));

        jLBL1.setFont(new java.awt.Font("Monotype Corsiva", 0, 48)); // NOI18N
        jLBL1.setForeground(new java.awt.Color(204, 102, 0));
        jLBL1.setText("Home Appliances Shop");
        getContentPane().add(jLBL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel25.setText("jLabel25");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel26.setText("jLabel25");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel27.setText("jLabel25");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel28.setText("jLabel25");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel29.setText("jLabel25");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\CLIENT\\Downloads\\aaa1.jpg")); // NOI18N
        jLabel30.setText("jLabel25");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//==================Function==============================
 public void ItemCost()
 {
     double sum = 0;
     for (int i = 0; i < jTable1.getRowCount();i++) 
    {
         sum = sum + Double.parseDouble(jTable1.getValueAt(i,2).toString());
     }
     jTF1.setText(Double.toString(sum));
     double cTotal = Double.parseDouble(jTF1.getText());
     double cTax = (cTotal * 0.12);
     //===PWD/Senior Discounts=====
     double initialTotal = cTotal - cTax;   //total - VAT  
     
    double discount = 0;
    if (pwd.isSelected()) {
        discount = 0.05; // 5% discount for PWD
    }
    if (senior.isSelected()) {
        discount = 0.2; // 20% discount for seniors
    }
    
    // Apply discount
    double discountAmount = initialTotal * discount; 
    double discountTotal = initialTotal - discountAmount ;
    
    //Apply the VAT to the discounted total
    double finalTotal = discountTotal + cTax; 
        
     //===TAX=====
     String iTaxTotal = String.format(" %.2f ", cTax);
     jTF2.setText(iTaxTotal);
     //=====SubTOtal======
     String iSubTotal = String.format (" %.2f ", cTotal - cTax);
     jTF1.setText(iSubTotal);
     //======Total======
     String ifinalTotal = String.format(" %.2f", finalTotal );
        jTF3.setText(ifinalTotal);
     
     
    

     
     
     
 }
     //==================Function Change==============================
     
     public void Change()
 {
     
double num1 = Double.parseDouble(jTF3.getText());  //ToTal of the Item
double num2 = Double.parseDouble(jTF4.getText());  // Cash Amount
double ans = num2 - num1;
jTF5.setText(String.valueOf(ans));  //change/sukli
 }
     
 class ReceiptGenerator {
    public static int generatePosSerialNumber() {
        Random random = new Random();
        return random.nextInt(9999999);
    }
    private static String generatePOSSerialNo() {
        Random random = new Random();
        StringBuilder posSerialNo = new StringBuilder();

        // Append 2 random digits
        for (int i = 0; i < 2; i++) {
            posSerialNo.append(random.nextInt(10));
        }

        // Append 3 random uppercase letters
        for (int i = 0; i < 3; i++) {
            posSerialNo.append((char) (random.nextInt(26) + 'A'));
        }

        // Append 5 random digits
        for (int i = 0; i < 5; i++) {
            posSerialNo.append(random.nextInt(10));
        }

        return posSerialNo.toString();
    }
}
    
    
    private void jTNikeflyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNikeflyActionPerformed
int Price = 20000;
int q1= (int) jS3.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Air Con",q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTNikeflyActionPerformed

    private void jButton106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton106ActionPerformed

    private void jButton116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton116ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton116ActionPerformed

    private void jButton126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton126ActionPerformed

    private void jButton136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton136ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton136ActionPerformed

    private void jButton146ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton146ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton146ActionPerformed

    private void jButton156ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton156ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton156ActionPerformed

    private void jButton166ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton166ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton166ActionPerformed

    
    private void jTj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTj1ActionPerformed
int Price = 35000; //price of spplisnce
int q1= (int) jS1.getValue(); //
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (sale25.isSelected() && flash.isSelected()) {
    // Both discounts are selected, show a warning message
    JOptionPane.showMessageDialog(null, "You cannot apply both discounts simultaneously.");
} else {
if (sale25.isSelected()) {
        Price = (int) (Price * 0.75); // Apply a 25% discount for sale
    }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }


int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Refrigerator",q1,tot,Price}); 
ItemCost(); 
}
    }//GEN-LAST:event_jTj1ActionPerformed

    private void jTtwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtwoActionPerformed
int Price = 2000;
int q1= (int) jS2.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (sale70.isSelected() && flash.isSelected()) {
    // Both discounts are selected, show a warning message
    JOptionPane.showMessageDialog(null, "You cannot apply both discounts simultaneously.");
} else {
if (sale70.isSelected()) {
        Price = (int) (Price * 0.3); // Apply a 70% discount for sale
    }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Toaster",q1,tot,Price}); 
ItemCost(); 
}
    }//GEN-LAST:event_jTtwoActionPerformed

    private void jTlebronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlebronActionPerformed
int Price = 40000;
int q1= (int) jS4.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"SmartLED-TV", q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTlebronActionPerformed

    private void jTNikeHBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNikeHBRActionPerformed
int Price = 5000;
int q1= (int) jS5.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Microwave", q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTNikeHBRActionPerformed

    private void jTjDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTjDActionPerformed
int Price = 2500;
int q1= (int) jS6.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Stand Fan", q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTjDActionPerformed

    private void jTjSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTjSActionPerformed
int Price = 3000;
int q1= (int) jS7.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"RiceCooker", q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTjSActionPerformed

    private void jTjPumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTjPumaActionPerformed
      
int Price = 7000;
int q1= (int) jS8.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (sale.isSelected() && flash.isSelected()) {
    // Both discounts are selected, show a warning message
    JOptionPane.showMessageDialog(null, "You cannot apply both discounts simultaneously.");
} else {
 if (sale.isSelected()) {
        Price = (int) (Price * 0.5); // Apply a 50% discount for sale
    }
 
 if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }
 
int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Vacuum", q1,tot,Price});
 ItemCost();
}
 
  
    }//GEN-LAST:event_jTjPumaActionPerformed

    private void jTNikeAlumniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNikeAlumniActionPerformed
int Price = 3000;
int q1= (int) jS9.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (sale10.isSelected() && flash.isSelected()) {
    // Both discounts are selected, show a warning message
    JOptionPane.showMessageDialog(null, "You cannot apply both discounts simultaneously.");
} else {
if (sale10.isSelected()) {
        Price = (int) (Price * 0.9); // Apply a 10% discount for sale
    }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Dispenser", q1,tot,Price});
ItemCost();
}
    }//GEN-LAST:event_jTNikeAlumniActionPerformed

    private void jTJCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTJCActionPerformed
int Price = 2000;
int q1= (int) jS10.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Blender", q1,tot,Price});
ItemCost();
    }//GEN-LAST:event_jTJCActionPerformed
   
    // PAY BUTTON
    private void jBpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpayActionPerformed
if (jCBPayment.getSelectedItem().equals("Select")){ 
JOptionPane.showMessageDialog(null, "Select Payment first!");
}

double total = Double.parseDouble(jTF3.getText());
double cash = Double.parseDouble(jTF4.getText());

if (cash < total ) {
         
       JOptionPane.showMessageDialog(null, 
                            "Input a higher amount more than the total", 
                            "Insufficient Cash", 
                            JOptionPane.WARNING_MESSAGE);
       
       jTF5.setText("");
    jTF4.setText("");
    
                    } else{
    
    Change();
    
    
    
   
    
                             
}


    }//GEN-LAST:event_jBpayActionPerformed

    private void jBRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.setRowCount(0);
jTF5.setText("");
jTF2.setText("");
jTF3.setText("");
jTF1.setText("");
jTF4.setText("");
jS1.setValue(0);
 jS2.setValue(0);
jS3.setValue(0);
jS4.setValue(0);
 jS5.setValue(0);
jS6.setValue(0);
jS7.setValue(0);
jS8.setValue(0);
jS9.setValue(0);
jS10.setValue(0);
jR.setText("");
pwd.setSelected(false); // Reset PWD checkbox
senior.setSelected(false); // Reset senior checkbox

//discount for product
sale.setSelected(false); 
sale10.setSelected(false);
sale25.setSelected(false); 
sale70.setSelected(false);
flash.setSelected(false); // Discount Store


    }//GEN-LAST:event_jBRActionPerformed

    private void jBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPActionPerformed
     try
        {
            jR.print();
        }
        catch(Exception e)
        {}
    }//GEN-LAST:event_jBPActionPerformed

    private void jBremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoveActionPerformed
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
int RemoveItem = jTable1.getSelectedRow();
if  (RemoveItem >= 0){
    model.removeRow(RemoveItem);
}
ItemCost();
if (jCBPayment.getSelectedItem().equals("Cash")){
    Change();
}else{
    jTF5.setText("");
    jTF4.setText("");
}
    }//GEN-LAST:event_jBremoveActionPerformed

    private void jCBPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPaymentActionPerformed
 if (jCBPayment.getSelectedItem().equals("Cash")) {
                    System.out.println("Cash selected");
                    CashFramee sec = new CashFramee(this); // Open new JFrame when "Cash" is selected
                    sec.setVisible(true);
                } 
 
 
  if (jCBPayment.getSelectedItem().equals("G-Cash")) {
                    System.out.println("G-Cash selected");
                     new Gcash();// Open new JFrame when "Cash" is selected
                     
  if (jTF3 != null && jTF4 != null) {
                    jTF4.setText(jTF3.getText());
                   }
                   
                }

    }//GEN-LAST:event_jCBPaymentActionPerformed

    private void jTF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF5ActionPerformed

    
    // TO PLACE ORDER!
    private void jBExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitActionPerformed
DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
LocalDateTime now = LocalDateTime.now();
String timestamp = dtf.format(now);

Random random = new Random();
int randomNumber = random.nextInt(1000); // Generate a random number between 0 and 999
String uniqueTaxNo =timestamp.replace("/","").replace(" ", "").replace(":", "")+ randomNumber;

String posSerialNo = ReceiptGenerator.generatePOSSerialNo(); //POS Serial No.

String ts = jTF3.getText();
double dts = Double.parseDouble(ts);
String ca = jTF4.getText();
double dca = Double.parseDouble(ca);
String aa = (String) jCBPayment.getSelectedItem();

// Top part of Receipt || Instead of used "setText" we will use "append" because "setText" only allows 1 body of text while "append" adds new text
jR.append(
    "                     Grp10 Shop     \n"+
    "                 Home Appliances   \n"+
    "                                   \n"+
    "    Col. E. De Leon st. Wawa, Brgy. Sto. Niño,\n"+
    "               Parañaque City, 1700"+"\n"+
    "               Ref: 4200060009000"+"\n"+
    "               Tax No: "+ uniqueTaxNo + "\n"+
    "                   +1 234 567 890\n"+
    "               POS Serial No: "+ posSerialNo + "\n"+
    "=======================================\n"+
    "\n"+
            "          Order                           QTY                   Amt"+ "\n"+
    "\n");

        // This Code will Loop through the rows of the table and append the item details to the receipt text area
        // first we set Interger "i" to get row count || i++ is looping additive value from 1 ->this will stop based on how many rows are detected
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String item = jTable1.getValueAt(i, 0).toString();
            String quantity = jTable1.getValueAt(i, 1).toString();
            String total = jTable1.getValueAt(i, 2).toString();
            //This text right here will reflect selected items, quantity, and total on the receipt
            jR.append("          "+item          + "                 " + quantity + "                    ₱" + total + "\n");
        }

        // Final line with the total amount || VAT is 12% of our sales
        String saleIndicator = "0.00";
if (sale.isSelected()) {
    saleIndicator = "Applied";
} else if (sale25.isSelected()) {
    saleIndicator = "Applied";
} else if (sale10.isSelected()) {
    saleIndicator = "Applied";
} else if (sale70.isSelected()) {
    saleIndicator = "Applied";
} else if (flash.isSelected()) {
    saleIndicator = "Applied";
}else if (pwd.isSelected()) {
    saleIndicator = "Applied";
}else if (senior.isSelected()) {
    saleIndicator = "Applied";
}





jR.append(
    "\n"+
    "=======================================\n"+
    "         Payment:                     "+ aa +"\n"+
    "         Total Amount:              ₱"+ (dts-(dts*0.12)) +"\n"+
    "         VAT:                               ₱"+(dts*0.12) +"\n"+
    "         Final Charge:              ₱"+ ts +"\n"+
    "         Discount:                      " + saleIndicator + "\n" +
    "=======================================\n"+
    "         Balance:                       ₱"+ dca +"\n"+
    "         Change:                       ₱"+ (dca-dts) +"\n"+
    "                                          \n"+
    "    Thank you for coming!!!\n"+
    "    Visit our website www.homeappliances.com \n"+
    "    Time and Date of Transaction: \n"+
    "                     "+ dtf.format(now)
);


    }//GEN-LAST:event_jBExitActionPerformed

    private void jTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF1ActionPerformed

    private void jTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF2ActionPerformed

    private void jTF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF4ActionPerformed

    private void jBExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExit1ActionPerformed
System.exit(0);           // TODO add your handling code here:
    }//GEN-LAST:event_jBExit1ActionPerformed

    private void jTj4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTj4ActionPerformed
int Price = 40000;
int q1= (int) jS11.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // tables were data is ableto gather
model.addRow(new Object[] {"WM",q1,tot,Price}); 
ItemCost();          // TODO add your handling code here:
    }//GEN-LAST:event_jTj4ActionPerformed

    private void JTNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNewActionPerformed
int Price = 2500;
int q1= (int) jS12.getValue();
int qty = q1;

if (q1 <= 0) {
            // Show message if the value is 0
            JOptionPane.showMessageDialog(null, "Please set the quantity");
            return; // Exit the actionPerformed method
        }

if (flash.isSelected()) {
        Price = (int) (Price * 0.3); // Apply discount store 
    }

int tot = Price * q1;
DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
model.addRow(new Object[] {"Stove",q1,tot,Price}); 
ItemCost();          // TODO add your handling code here:
    }//GEN-LAST:event_JTNewActionPerformed

    private void seniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seniorActionPerformed

    private void pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdActionPerformed

    private void sale25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sale25ActionPerformed

    private void sale70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sale70ActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saleActionPerformed

    private void sale10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sale10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sale10ActionPerformed

    private void flashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CISOrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CISOrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CISOrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CISOrderingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CISOrderingSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JTNew;
    private javax.swing.JCheckBox flash;
    private javax.swing.JButton jBExit;
    private javax.swing.JButton jBExit1;
    private javax.swing.JButton jBP;
    private javax.swing.JButton jBR;
    private javax.swing.JButton jBpay;
    private javax.swing.JButton jBremove;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton118;
    private javax.swing.JButton jButton119;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton121;
    private javax.swing.JButton jButton122;
    private javax.swing.JButton jButton123;
    private javax.swing.JButton jButton124;
    private javax.swing.JButton jButton125;
    private javax.swing.JButton jButton126;
    private javax.swing.JButton jButton127;
    private javax.swing.JButton jButton128;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton130;
    private javax.swing.JButton jButton131;
    private javax.swing.JButton jButton132;
    private javax.swing.JButton jButton133;
    private javax.swing.JButton jButton134;
    private javax.swing.JButton jButton135;
    private javax.swing.JButton jButton136;
    private javax.swing.JButton jButton137;
    private javax.swing.JButton jButton138;
    private javax.swing.JButton jButton139;
    private javax.swing.JButton jButton140;
    private javax.swing.JButton jButton141;
    private javax.swing.JButton jButton142;
    private javax.swing.JButton jButton143;
    private javax.swing.JButton jButton144;
    private javax.swing.JButton jButton145;
    private javax.swing.JButton jButton146;
    private javax.swing.JButton jButton147;
    private javax.swing.JButton jButton148;
    private javax.swing.JButton jButton149;
    private javax.swing.JButton jButton150;
    private javax.swing.JButton jButton151;
    private javax.swing.JButton jButton152;
    private javax.swing.JButton jButton153;
    private javax.swing.JButton jButton154;
    private javax.swing.JButton jButton155;
    private javax.swing.JButton jButton156;
    private javax.swing.JButton jButton157;
    private javax.swing.JButton jButton158;
    private javax.swing.JButton jButton159;
    private javax.swing.JButton jButton160;
    private javax.swing.JButton jButton161;
    private javax.swing.JButton jButton162;
    private javax.swing.JButton jButton163;
    private javax.swing.JButton jButton164;
    private javax.swing.JButton jButton165;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JComboBox<String> jCBPayment;
    private javax.swing.JLabel jLBL1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextArea jR;
    private javax.swing.JSpinner jS1;
    private javax.swing.JSpinner jS10;
    private javax.swing.JSpinner jS11;
    private javax.swing.JSpinner jS12;
    private javax.swing.JSpinner jS2;
    private javax.swing.JSpinner jS3;
    private javax.swing.JSpinner jS4;
    private javax.swing.JSpinner jS5;
    private javax.swing.JSpinner jS6;
    private javax.swing.JSpinner jS7;
    private javax.swing.JSpinner jS8;
    private javax.swing.JSpinner jS9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    public static javax.swing.JTextField jTF3;
    public static javax.swing.JTextField jTF4;
    private javax.swing.JTextField jTF5;
    private javax.swing.JButton jTJC;
    private javax.swing.JButton jTNikeAlumni;
    private javax.swing.JButton jTNikeHBR;
    private javax.swing.JButton jTNikefly;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jTj1;
    private javax.swing.JButton jTj4;
    private javax.swing.JButton jTjD;
    private javax.swing.JButton jTjPuma;
    private javax.swing.JButton jTjS;
    private javax.swing.JButton jTlebron;
    private javax.swing.JButton jTtwo;
    private javax.swing.JCheckBox pwd;
    private javax.swing.JCheckBox sale;
    private javax.swing.JCheckBox sale10;
    private javax.swing.JCheckBox sale25;
    private javax.swing.JCheckBox sale70;
    private javax.swing.JCheckBox senior;
    // End of variables declaration//GEN-END:variables

    private double calculateDiscount() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
